sudo: false
language: python
python:
  - "2.7"
  - "3.7"
env:
  - DJANGO=1.11.* DJANGO_SETTINGS_MODULE='settings_sqllite'
  - DJANGO=1.11.* DJANGO_SETTINGS_MODULE='settings_postgres'
  - DJANGO=1.11.* DJANGO_SETTINGS_MODULE='settings_mysql'
  - DJANGO=2.0.* DJANGO_SETTINGS_MODULE='settings_sqllite'
  - DJANGO=2.0.* DJANGO_SETTINGS_MODULE='settings_postgres'
  - DJANGO=2.0.* DJANGO_SETTINGS_MODULE='settings_mysql'
  - DJANGO=2.2.* DJANGO_SETTINGS_MODULE='settings_sqllite'
  - DJANGO=2.2.* DJANGO_SETTINGS_MODULE='settings_postgres'
  - DJANGO=2.2.* DJANGO_SETTINGS_MODULE='settings_mysql'
services:
  - postgresql
  - mysql
addons:
  postgresql: "9.6"
install:
  - pip install -q Django==$DJANGO
  - pip install django-common-helpers
  - pip install coveralls
  - pip install -r test_requirements.pip
script:
  - coverage run manage.py test django_cron
after_success:
  - coveralls
before_script:
  - sudo mysql -e 'create database travis_test;'
  - sudo -u postgres psql -c 'create database travis_test;'
#  - sudo python -m flake8 . --config=flake8
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0.* DJANGO_SETTINGS_MODULE='settings_sqllite'
    - python: "2.7"
      env: DJANGO=2.0.* DJANGO_SETTINGS_MODULE='settings_postgres'
    - python: "2.7"
      env: DJANGO=2.0.* DJANGO_SETTINGS_MODULE='settings_mysql'
    - python: "2.7"
      env: DJANGO=2.2.* DJANGO_SETTINGS_MODULE='settings_sqllite'
    - python: "2.7"
      env: DJANGO=2.2.* DJANGO_SETTINGS_MODULE='settings_postgres'
    - python: "2.7"
      env: DJANGO=2.2.* DJANGO_SETTINGS_MODULE='settings_mysql'
