# Generated by Django 5.2 on 2026-05-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cron', '0003_cronjobcancelcondition'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='cronjoblog',
                    index=models.Index(
                        fields=['code', 'start_time', 'ran_at_time'],
                        name='django_cron_code_21f381_idx',
                    ),
                ),
                migrations.AddIndex(
                    model_name='cronjoblog',
                    index=models.Index(
                        fields=['code', 'start_time'],
                        name='django_cron_code_966ed3_idx',
                    ),
                ),
                migrations.AddIndex(
                    model_name='cronjoblog',
                    index=models.Index(
                        fields=['code', 'is_success', 'ran_at_time'],
                        name='django_cron_code_89ad04_idx',
                    ),
                ),
            ],
        ),
    ]
